import { Router, type IRouter } from "express";
import { loadUser } from "../middlewares/auth";
import { loginLimiter } from "../middlewares/rateLimit";
import healthRouter from "./health";
import authRouter from "./auth";
import tenantsRouter from "./tenants";
import usersRouter from "./users";
import gamesRouter from "./games";
import eventsRouter from "./events";
import eventsByCodeRouter from "./events-by-code";
import teamsRouter from "./teams";
import playersRouter from "./players";
import scoresRouter from "./scores";
import scoreboardRouter from "./scoreboard";
import mediaRouter from "./media";
import questionsRouter from "./questions";
import translationsRouter from "./translations";
import kpisRouter from "./kpis";
import devicesRouter from "./devices";
import gameSessionsRouter from "./game-sessions";
import roundsRouter from "./rounds";
import cardSetsRouter from "./card-sets";
import coppieRouter from "./coppie";
import quizPacksRouter from "./quiz-packs";
import quizCategoriesRouter from "./quiz-categories";
import quizzoneRouter from "./quizzone";
import systemSettingsRouter from "./system-settings";
import auditLogRouter from "./audit-log";
import percorsoRouter from "./percorso";
import eveningRouter from "./evening";
import adultOnlyRouter from "./adult-only";
import balloRouter from "./ballo";
import wordBackRouter from "./wordback";
import karaokeRouter from "./karaoke";
import freestyleRouter from "./freestyle";
import saraMusicaRouter from "./saramusica";
import jonnyRouter from "./jonny";
import panicRouter from "./panic";
import networkRouter from "./network";
import homeRouter from "./home";
import storageRouter from "./storage";

const router: IRouter = Router();

// Public routes (no auth) — must come before loadUser
router.use(networkRouter);

router.use(loadUser);
router.use(healthRouter);
// Apply rate limiting to login route
router.use("/auth/login", loginLimiter);
router.use(authRouter);
router.use(tenantsRouter);
router.use(usersRouter);
router.use(gamesRouter);
// events/by-code must come BEFORE events/:id to avoid param collision
router.use(eventsByCodeRouter);
router.use(eventsRouter);
router.use(teamsRouter);
router.use(playersRouter);
router.use(scoresRouter);
router.use(scoreboardRouter);
router.use(mediaRouter);
router.use(questionsRouter);
router.use(translationsRouter);
router.use(kpisRouter);
router.use(devicesRouter);
router.use(gameSessionsRouter);
router.use(roundsRouter);
router.use(cardSetsRouter);
router.use(coppieRouter);
router.use(quizPacksRouter);
router.use(quizCategoriesRouter);
router.use(quizzoneRouter);
router.use(systemSettingsRouter);
router.use(auditLogRouter);
router.use(percorsoRouter);
router.use(eveningRouter);
router.use(adultOnlyRouter);
router.use(balloRouter);
router.use(wordBackRouter);
router.use(karaokeRouter);
router.use(freestyleRouter);
router.use(saraMusicaRouter);
router.use(jonnyRouter);
router.use(panicRouter);
router.use(homeRouter);
router.use(storageRouter);

export default router;
