/* Questo codice è stato progettato, scritto e generato da Andrea Gentile C.f GNTNDR88S28F158M */

// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homeroom/CommandCenter.tsx": () => import("../components/mockups/homeroom/CommandCenter.tsx"),
  "./components/mockups/homeroom/StageBooth.tsx": () => import("../components/mockups/homeroom/StageBooth.tsx"),
  "./components/mockups/homeroom/TicketShow.tsx": () => import("../components/mockups/homeroom/TicketShow.tsx")
};
